config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/consult', to: 'home#consult'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_states
  before_action :weather_response

  def index
  end

  def consult
    Rails.cache.fetch("districts_#{params[:state]}", expires_in: 12.hours) do
      CityService.new(params[:state]).call
    end

    if params[:city].present?
      Rails.cache.fetch("city_#{params[:city]}", expires_in: 12.hours) do
        WeatherService.new(params[:city]).call
      end
    end

    redirect_to root_path(state: params[:state], city: params[:city])
  end

  private

  def load_states
    @states = StateService.new.call
  end

  def weather_response
    @weather_response = Rails.cache.read("city_#{params[:city]}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="card offset-md-4 col-md-4 mt-4 opacity-75 shadow">
  <div class="text-center m-4">
    <%= form_with url: home_consult_path, method: :get do |form| %>
      <%= form.select :state, @states.pluck('sigla'), { include_blank: 'Selecione o estado', selected: params[:state] }, class: 'form-control my-3', onchange: "this.form.submit();" %>
      
      <% if params[:state].present? %>
        <% districts = Rails.cache.read("districts_#{params[:state]}") %>
        <%= form.select :city, districts.pluck('nome'), { include_blank: 'Selecione a cidade', selected: params[:city] }, class: 'form-control my-3', onchange: "this.form.submit();" if districts.present? %>
      <% end %>
    <% end %>
  </div>
  
  <div class="card-body text-center">
    <% if @weather_response.present? && @weather_response['name'].present? %>
      <h2><%= @weather_response['name'] %></h2>

      <hr />

      <div class="text-center">
        <h2><%= @weather_response['main']['temp'] %> ºC</h2>

        Mínima de: <b><%= @weather_response['main']['temp_min'] %> ºC</b> <br />
        Máxima de: <b><%= @weather_response['main']['temp_max'] %> ºC</b>
      </div>

      <hr />

      <h5>Tempo: <%= @weather_response['weather'][0]['description'].titleize %></h5>
      <h5>Humidade: <%= @weather_response['main']['humidity'] %>%</h5>
    <% end %>

    <% if @weather_response.present? && @weather_response['name'].nil? %>
      <small>Selecione outra cidade!</small>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hacktoberfest - 2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/duotone.css" integrity="sha384-R3QzTxyukP03CMqKFe0ssp5wUvBPEyy9ZspCB+Y01fEjhMwcXixTyeot+S40+AjZ" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/fontawesome.css" integrity="sha384-eHoocPgXsiuZh+Yy6+7DsKAerLXyJmu2Hadh4QYyt+8v86geixVYwFqUvMU8X90l" crossorigin="anonymous"/>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-white opacity-50 text-black p-4 text-center shadow">
  <h2 class="d-inline-block me-2">Previsão do Tempo</h2>
  <i class="d-inline-block fas fa-wind fa-3x ms-2"></i>
</nav>